#!/bin/sh -x

cd "`dirname $0`" &&
  if which libtoolize 2> /dev/null; then 
    libtoolize --copy --force
  else
    glibtoolize --copy --force
  fi
  aclocal &&
  autoheader &&
  automake --add-missing &&
  autoconf &&
cd liboop && ./bootstrap
